### ISSUE TITLE
希望能早点能支持ae350 A25 machine

### ISSUE THREAD

**Issue by liqihong8** [andestech/meta-andes#2]
这个版本只能支持ae350-ax45mp machine，希望能早点能支持ae350 A25 machine，我比较习惯使用yocto构建linux系统，应该其他人也有这个需求。

**Comment by lyctw** [comment]
Hi @verilogzhou 

I have a plan to support all A-series CPUs in the upcoming AndeSight v5.3.0 release.
Thanks.

**Comment by lyctw** [comment]
Hi 

A25MP support has been released with `ast-v5_3_0-branch`.
https://github.com/andestech/meta-andes/tree/ast-v5_3_0-branch/conf/machine

Feel free to open another issue if you encounter any problems.
Thanks
